apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-customplugin-1
data:
  jsPlugin.js: |
    var exampleJavaScriptMiddlewarePreHook = new TykJS.TykMiddleware.NewMiddleware({});

    exampleJavaScriptMiddlewarePreHook.NewProcessRequest(function(request, session) {
        // You can log to Tyk console output by calling the built-in log() function:
        log("Hello from the Tyk JavaScript middleware pre hook function")
        
        // Add a request headers
        request.SetHeaders["Hello"] = "World V2";

        // You must return both the request and session metadata 
        return exampleJavaScriptMiddlewarePreHook.ReturnData(request, {}  );
    });
  pythonPlugin.py: |
    from tyk.decorators import *
    from gateway import TykGateway as tyk
    from time import time

    @Hook
    def PreHook(request, session, spec):
        tyk.log("PreHook is called", "info")
        # Inject a header:
        request.add_header("testheader", "testvalue")
        return request, session