apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-gtw
  labels:
    app: tyk-gtw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyk-gtw
  template:
    metadata:
      labels:
        app: tyk-gtw
    spec:
      containers:
        - name: tyk-gtw
          image: "tykio/tyk-gateway:v3.1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TYK_GW_LISTENPORT
              value: "8080"
            - name: TYK_GW_SECRET
              value: "foo"
            - name: TYK_GW_STORAGE_HOST
              value: "redis"
            - name: TYK_GW_STORAGE_PORT
              value: "6379"
            - name: TYK_GW_ENABLEANALYTICS
              value: "true"
          volumeMounts:
            - name: tyk-config
              mountPath: /opt/tyk-gateway/tyk.conf
              subPath: tyk.conf
            - name: tyk-customplugin-1
              mountPath: /mnt/tyk-gateway/middleware/jsPlugin.js
              subPath: jsPlugin.js
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: tyk-config
          configMap:
            name: tyk-config
            items:
              - key: tyk.conf
                path: tyk.conf
        - name: tyk-customplugin-1
          configMap:
            name: tyk-customplugin-1
            items:
              - key: jsPlugin.js
                path: jsPlugin.js
                
---
apiVersion: v1
kind: Service
metadata:
  name: tyk-svc
  labels:
    app: tyk-gtw
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tyk-gtw
