apiVersion: v1
kind: ConfigMap
metadata:
  name: pump-config
data:
  pump.conf: |
    {
      "analytics_storage_type": "redis",
      "analytics_storage_config": {
        "optimisation_max_idle": 2000,
        "optimisation_max_active": 4000
      },
      "purge_delay": 1,
      "pumps": {
      },
      "dont_purge_uptime_data": true
    }
