apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: apps
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
  namespace: tyk
spec:
  name: httpbin protected v2
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.apps:8000
    listen_path: /httpbin
    strip_listen_path: true
  use_standard_auth: true

  auth_configs:
    authToken:
      # param_name: Auth
      auth_header_name: Authorization
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: protect-api
  namespace: tyk
spec:
  name: Developer-Access
  state: active
  active: true
  access_rights_array:
    - name: httpbin
      namespace: tyk
      versions:
        - Default
  
      
---
apiVersion: tyk.tyk.io/v1alpha1
kind: APIDescription
metadata:
  name: sample-portal-api
  namespace: tyk
spec:
  name: "sample portal config"
  show: true
  auth_type: keyless
  policyRef:
    name: protect-api
    namespace: tyk
  docs:
    documentation: "https://httpbin.org/spec.json"
    doc_type: swagger_custom_url
---
apiVersion: tyk.tyk.io/v1alpha1
kind: PortalConfig
metadata:
  name: sample-portal-config
  namespace: tyk
spec: {}
---
apiVersion: tyk.tyk.io/v1alpha1
kind: PortalAPICatalogue
metadata:
  name: sample-portal-api
  namespace: tyk
spec:
  apis:
    - apiDescriptionRef:
        name: sample-portal-api
        namespace: tyk