apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: apps
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
  namespace: tyk
spec:
  name: httpbin
  # Set "use_keyless" to false when you want to secure your API
  # And then also uncomment the security policy CRD
  use_keyless: true
  protocol: http
  active: true
  do_not_track: false
  proxy:
    target_url: http://httpbin.apps:8000
    listen_path: /httpbin
    strip_listen_path: true
# ---
# apiVersion: tyk.tyk.io/v1alpha1
# kind: SecurityPolicy
# metadata:
#   name: httpbin
#   namespace: tyk
# spec:
#   name: Rate Limit, Quota and Throttling policy
#   state: active
#   active: true
#   access_rights_array:
#     - name: httpbin
#       namespace: tyk
#       versions:
#         - Default
#   quota_max: 50
#   quota_renewal_rate: 60
#   rate: 2
#   per: 10